spring:
  datasource:
    url: jdbc:mysql://localhost:3306/loan_management
    username: Winnie
    password: W!nf379!
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  security:
    jwt:
      secret: "my_super_long_very_secure_secret_key_that_is_32_bytes_long"

server:
  port: 8080
  address: 0.0.0.0  # Allows access from other devices in the network

logging:
  level:
    org.springframework: DEBUG
    com.loanSystem: DEBUG
