spring:
  datasource:
    url: jdbc:mysql://localhost:3306/loan_management
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  security:
    jwt:
      secret: my-secret-key
